### ISSUE TITLE
logError("%B") causes assertion fail

### ISSUE THREAD

**Issue by the-Mitu** [vibe-d/vibe-core#87] opened 2018-07-26 07:54 UTC
This code:

    logError("%B");

causes an assertion to fail - orphaned format character. I've stumbled upon this when I wanted to log the exception, whose message contained urlencoded things.

I'd expect message passed to logError to be escaped before being formatted inside logging methods - currently logging things containing for example urlencoded data will crash the entire application.

**Comment by the-Mitu** [comment] 2018-07-26 08:31
Yes, it's easy to workaround. However it seemed unintuitive to me and I spent some time wondering why does it crash.

Should I make an "it's not a bug, it's a feature" assumption here and consider it done this way by design? ;)

**Comment by s-ludwig** [comment] 2019-06-20 08:01
Fixed by #152 (it was indeed by design, but since we are just talking about logging, ignoring format arguments without additional argument is just fine, too)

**Closed by s-ludwig** 2019-06-20 08:01 UTC
