### ISSUE TITLE
Linker errors with DMD 2.094.2

### ISSUE THREAD

**Issue by p-mitana** [vibe-d/vibe-core#238] opened 2020-11-30 20:16 UTC
```
/usr/include/dmd/phobos/std/typecons.d:6471: error: undefined reference to '_D3std8typecons__T10RefCountedTSQBe9container5array__T5ArrayTS4vibe4core4sync18LocalTaskSemaphore12ThreadWaiterZQCg7PayloadVEQEtQEs24RefCountedAutoInitializei0ZQFm15RefCountedStore15deallocateStoreMFNaNbNiZv'
/usr/include/dmd/phobos/std/typecons.d:6471: error: undefined reference to '_D3std8typecons__T10RefCountedTSQBe9container5array__T5ArrayTS4vibe4http6router17MatchGraphBuilder11TerminalTagZQCg7PayloadVEQEtQEs24RefCountedAutoInitializei0ZQFm15RefCountedStore15deallocateStoreMFNaNbNiZv'
/usr/include/dmd/phobos/std/typecons.d:6471: error: undefined reference to '_D3std8typecons__T10RefCountedTSQBe9container5array__T5ArrayTS4vibe4http6router__T16LinkedSetBackingTkZQv5EntryZQCg7PayloadVEQEtQEs24RefCountedAutoInitializei0ZQFm15RefCountedStore15deallocateStoreMFNaNbNiZv'
/usr/include/dmd/phobos/std/typecons.d:6471: error: undefined reference to '_D3std8typecons__T10RefCountedTSQBe9container5array__T5ArrayTS4vibe4http6router17MatchGraphBuilder4NodeZQBy7PayloadVEQElQEk24RefCountedAutoInitializei0ZQFe15RefCountedStore15deallocateStoreMFNaNbNiZv'
```

vibe-core 1.11.1, vibe.d 0.9.2, DMD 2.094.2, Ubuntu 20.10. Problem does not exist with DMD 2.093.1.

**Comment by s-ludwig** [comment] 2020-12-01 08:05
Can you also report this on https://issues.dlang.org/ if you haven't already (it looks like it really must be fixed there)? vibe-core is tested as part of DMD's CI, and it looks okay there AFAICS, so the other question is what steps are needed to reproduce this and what OS/linker is in use.

**Comment by the-Mitu** [comment] 2020-12-03 07:58
@s-ludwig - https://issues.dlang.org/show_bug.cgi?id=21448

OS is Ubuntu 20.10. I haven't change the linker, so it's ld.

**Comment by s-ludwig** [comment] 2024-07-27 10:12
Closing this, due to the involved versions all being so much out of date.

**Closed by s-ludwig** 2024-07-27 10:12 UTC
